<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
        [
            'name' => "air force 1 '07 men's basketball shoes - white",
            'cogs' => 0,
            'price' => 1549000,
            'discount' => 30,
            'brand' => 'NIKE',
            'gender' => 'male',
            'description' => "Step into a legend with the Nike Air Force 1 '07. Featuring crisp white leather and classic hoops-inspired style, this icon brings timeless street appeal and durable comfort. Padded collars and Nike Air cushioning provide all-day support on and off the court.",
            'rating_avg' => 4.4,
            'total_reviews' => 102,
            'sold' => 1323,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "air force 1 '07 men's basketball shoes - black",
            'cogs' => 0,
            'price' => 1549000,
            'discount' => 10,
            'brand' => 'NIKE',
            'gender' => 'male',
            'description' => "Bold and iconic, the Nike Air Force 1 '07 in black delivers classic basketball style with a modern street edge. Premium materials and perforated toe details ensure comfort and breathability, while the Nike Air unit softens every step.",
            'rating_avg' => 4.8,
            'total_reviews' => 94,
            'sold' => 1240,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "speedcat og unisex lifestyle shoes - black",
            'cogs' => 0,
            'price' => 1899000,
            'discount' => 0,
            'brand' => 'PUMA',
            'gender' => 'unisex',
            'description' => "Originally made for Formula 1 drivers, the Speedcat OG returns as a lifestyle icon. Sleek black suede and a low-profile silhouette offer motorsport heritage and street-ready style for everyday wear.",
            'rating_avg' => 4.6,
            'total_reviews' => 76,
            'sold' => 796,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "speedcat og unisex lifestyle shoes - red",
            'cogs' => 0,
            'price' => 1899000,
            'discount' => 0,
            'brand' => 'PUMA',
            'gender' => 'unisex',
            'description' => "Drive your street style with the Speedcat OG in vibrant red. Inspired by the fast lane, this sleek silhouette brings racing DNA into your daily rotation with rich suede and a heritage motorsport vibe.",
            'rating_avg' => 4.5,
            'total_reviews' => 98,
            'sold' => 925,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "palermo moda vintage women's lifestyle shoes - blue",
            'cogs' => 0,
            'price' => 1599000,
            'discount' => 10,
            'brand' => 'PUMA',
            'gender' => 'female',
            'description' => "Channel vintage Italian flair with the Palermo Moda. This women's sneaker pairs a vibrant blue suede upper with retro charm and everyday comfort, making it a perfect choice for relaxed and stylish days.",
            'rating_avg' => 4.3,
            'total_reviews' => 45,
            'sold' => 570,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "530 unisex sneakers shoes - silver",
            'cogs' => 0,
            'price' => 1599000,
            'discount' => 30,
            'brand' => 'NEW BALANCE',
            'gender' => 'unisex',
            'description' => "The New Balance 530 blends retro running style with modern comfort. A standout silver finish and ABZORB cushioning create a bold and cushy ride for all-day exploration in timeless fashion.",
            'rating_avg' => 4.2,
            'total_reviews' => 154,
            'sold' => 1620,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "mr530 men's running shoes - white with natural indigo",
            'cogs' => 0,
            'price' => 1599000,
            'discount' => 0,
            'brand' => 'NEW BALANCE',
            'gender' => 'male',
            'description' => "Run the streets with the MR530 in fresh white and natural indigo. Designed for both performance and daily wear, it combines breathable mesh, durable overlays, and advanced cushioning to keep you moving in comfort and style.",
            'rating_avg' => 4.7,
            'total_reviews' => 123,
            'sold' => 1096,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "550 men's sneakers- black",
            'cogs' => 0,
            'price' => 2099000,
            'discount' => 50,
            'brand' => 'NEW BALANCE',
            'gender' => 'male',
            'description' => "A true throwback from the archives, the New Balance 550 in sleek black revives basketball-inspired heritage with a streetwear twist. Leather overlays and a classic build deliver bold style with everyday durability.",
            'rating_avg' => 3.7,
            'total_reviews' => 68,
            'sold' => 612,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "old skool unisex sneakers shoes - black",
            'cogs' => 0,
            'price' => 999000,
            'discount' => 0,
            'brand' => 'VANS',
            'gender' => 'unisex',
            'description' => "The Vans Old Skool is a timeless icon. This black unisex version features signature side stripes, sturdy canvas and suede uppers, and the original waffle sole. Perfect for skaters and casual creatives alike.",
            'rating_avg' => 4.9,
            'total_reviews' => 13,
            'sold' => 112,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => "sambae women's sneakers - ftwr white",
            'cogs' => 0,
            'price' => 2200000,
            'discount' => 50,
            'brand' => 'ADIDAS',
            'gender' => 'female',
            'description' => "Rediscover movement with the Sambae Women’s Sneakers in Footwear White. This fresh take on a classic archive style features a supportive fit, durable synthetic upper, and lightweight EVA midsole ideal for urban exploration and everyday comfort.",
            'rating_avg' => 4.8,
            'total_reviews' => 113,
            'sold' => 1118,
            'hide_status' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
    }
}
